#!/bin/sh
# Patch the input java class file with Preverifier
# Use -r to restore the class file's backup
while getopts r flag; do
	case $flag in
		r) 
		  shift $(( OPTIND - 1 ))
		  ./restore.sh $1;;
		e)
		  shift $(( OPTIND - 1 ))
		  EXEC=true
	esac
done

FILE=$1

if [ -f "$FILE"_backup.class ] 
then
	while true; do
		read -e -p ""$FILE"_backup already exists, will you overwrite this backup? (y/n) " yn
		case $yn in
			y)	cp $FILE.class $1_backup.class;
				echo "$FILE"_backup.class overwritten;break;;
			n) echo Backup unchanged;break;;
			*) echo "Please respond with y or n";;
		esac
	done
else 
	cp $FILE.class $1_backup.class;
fi
if [ EXEC == true ] ; then
	echo **Original Output**
	java $FILE
java -classpath tests --add-modules java.base --add-exports java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-exports java.base/jdk.internal.org.objectweb.asm.util=ALL-UNNAMED --add-exports java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED Preverifier.java $FILE
echo **Patched Output**
java $FILE
echo Done